# docker-compose -f docker-compose-pg-only.yml upversion: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: changeme
